os:
- linux
- windows

language: go

go:
- 1.x

go_import_path: github.com/GoogleCloudPlatform/ops-agent

before_install:
- go get golang.org/x/tools/cmd/goimports

script:
- if [[ $(goimports -l .) ]]; then goimports -d .; echo 'Failed the goimports format check. Please format the code using "goimports -w ."'; exit 1; fi
- go test -mod=mod ./...
