os:
- linux
- windows

language: go

go:
- 1.x

go_import_path: github.com/GoogleCloudPlatform/ops-agent

before_install:
- go get golang.org/x/tools/cmd/goimports

before_script:
- if [[ $(goimports -l .) ]]; then echo 'Please format the code using "goimports -w ."'; goimport -d .; exit 1; fi

script:
- go test -mod=mod ./...
